"""Fixed constants and messiness knobs for the Meridian Launch Systems generators.

Every value here is a hardcoded constant. Data generation must never depend on
time-of-run, environment variables, or filesystem state — the same seed must
produce byte-identical output on every run. Changing any value in this file
changes the generated bytes, so treat edits as schema changes.
"""

from datetime import date

# Master seed, fixed by the Phase P plan (G1 amendment, 2026-08-22). Do not change.
SEED = 20260822

# ---------------------------------------------------------------------------
# Row counts (asserted exactly in tests)
# ---------------------------------------------------------------------------
N_LAUNCHES = 1200
N_SUPPLIERS = 24
N_PARTS = 300
N_WORK_ORDERS = 800
N_FINDINGS = 420

# ---------------------------------------------------------------------------
# Fixed calendar windows (no time-of-run anywhere)
# ---------------------------------------------------------------------------
# Launch dates are sampled as (uniform week) + (weighted weekday) over whole
# weeks, so the weekday bias is exact and unclipped. START_MONDAY must be a
# Monday.
START_MONDAY = date(2021, 1, 4)
N_WEEKS = 285  # last week starts 2026-06-15; last possible launch date 2026-06-21

COST_START = date(2024, 1, 1)
COST_END = date(2026, 6, 21)

WO_START = date(2023, 1, 1)
WO_END = date(2026, 6, 1)

FINDINGS_START = date(2025, 1, 1)
FINDINGS_END = date(2026, 6, 1)

# ---------------------------------------------------------------------------
# Messiness knobs (all reproducible; bounds are asserted in tests)
# ---------------------------------------------------------------------------
# Weekday launch bias, Monday..Sunday. Saturday (index 5) must remain the
# strict argmax: pytest asserts it and the copilot golden-question eval
# ("which day of the week has the most launches?") depends on it.
WEEKDAY_WEIGHTS = [10, 11, 12, 12, 14, 26, 15]

# Fraction of values in NULLABLE_COLUMNS set to null.
NULL_RATE = 0.03
# Fraction of values in DIRTY_COLUMNS given casing/whitespace damage.
DIRTY_RATE = 0.06
# Fraction of parts whose lead time is an outlier (multiplied 4-9x).
LEAD_TIME_OUTLIER_RATE = 0.07
# Probability a launch slips at least one day past its planned date.
DELAY_PROB = 0.30
# Probability a multi-scrub launch is a weather cascade (consecutive days).
CASCADE_PROB = 0.65

# Columns that receive reproducible random nulls at NULL_RATE.
NULLABLE_COLUMNS = {
    "launches": ["weather_delay_min", "insurance_value_musd"],
    "scrubs": ["recycle_hours"],
    "telemetry_summary": ["data_dropout_s"],
    "parts": ["material"],
}

# Columns that receive reproducible casing/whitespace damage at DIRTY_RATE.
DIRTY_COLUMNS = {
    "launches": ["customer"],
    "parts": ["material"],
    "work_orders": ["technician"],
}

# ---------------------------------------------------------------------------
# Tables
# ---------------------------------------------------------------------------
TABLE_ORDER = [
    "launches",
    "scrubs",
    "vehicles",
    "pads",
    "telemetry_summary",
    "parts",
    "suppliers",
    "work_orders",
    "cost_daily",
    "findings_history",
]

# Exact expected row counts for the fixed-size tables (scrubs is derived from
# launches.scrub_count and asserted separately).
EXPECTED_COUNTS = {
    "launches": N_LAUNCHES,
    "telemetry_summary": N_LAUNCHES,
    "vehicles": 12,
    "pads": 11,
    "suppliers": N_SUPPLIERS,
    "parts": N_PARTS,
    "work_orders": N_WORK_ORDERS,
    # 5 cost centers x days in [COST_START, COST_END]
    "cost_daily": 5 * ((COST_END - COST_START).days + 1),
    "findings_history": N_FINDINGS,
}

WEEKDAY_NAMES = [
    "Monday",
    "Tuesday",
    "Wednesday",
    "Thursday",
    "Friday",
    "Saturday",
    "Sunday",
]
